### PR TITLE
support for projects without FlatpageFallbackMiddleware or django.contrib.sites

### PR DESCRIPTION
**Pull request by eriktelepovsky**
FlatpageFallbackMiddleware shouldn't be mandatory

### CODE REVIEW

**Comment by chronossc** [comment]
@eriktelepovsky I planned to check breadcrumbs this weekend, but maybe I don't have time.
I added you as collaborator of the repo, if you free confident and tests are ok, fell free to merge the PR ( under a new version plz :] )

**Comment by eriktelepovsky** [comment]
Thanks. Can you run sdist upload to PyPi please?

**Comment by chronossc** [comment]
Sure I can! Tonight!

**Comment by felipe-prenholato** [comment]
@eriktelepovsky I pushed to pypi version `1.1.4a1` (https://pypi.python.org/pypi/django-breadcrumbs/1.1.4a1). Didn't released version 1.1.4 cuz I cannot run the tests right now :).

**Comment by eriktelepovsky** [comment]
All right. Thanks.

**Pull request merged**
